export const MINIMAX_H3_SCHEMA_STATEMENTS = Object.freeze([
  `create table if not exists minimax_h3_runners (
    runner_id text primary key,
    owner_user_id text not null references users(id) on delete cascade,
    installation_id_hash text not null,
    label text not null,
    status text not null default 'active' check (status in ('active', 'disabled')),
    protocol_version text not null,
    agent_version text not null,
    controller_version text not null,
    capabilities_json text not null default '{}',
    ready_state text not null default 'offline' check (ready_state in ('offline', 'agent_only', 'bridge_only', 'comfy_unready', 'ready', 'busy', 'disk_low', 'error')),
    busy_job_id text not null default '',
    current_token_id text not null default '',
    last_seen_at text not null,
    last_persisted_heartbeat_at text not null,
    revision integer not null default 0,
    created_at text not null,
    updated_at text not null,
    unique(owner_user_id, installation_id_hash)
  )`,
  `create table if not exists minimax_h3_jobs (
    job_id text primary key,
    owner_user_id text not null references users(id) on delete cascade,
    runner_id text not null references minimax_h3_runners(runner_id) on delete restrict,
    operation_id text not null,
    payload_sha256 text not null,
    protocol_version text not null,
    template_version text not null,
    spec_json text not null,
    prompt_sha256 text not null,
    state text not null check (state in ('awaiting_assets', 'queued', 'leased', 'validating', 'submitted', 'running', 'retrieving', 'ready', 'failed', 'stalled', 'cancelled', 'expired', 'deleted')),
    revision integer not null default 0,
    attempt integer not null default 1,
    retry_of_job_id text not null default '',
    lease_id_hash text not null default '',
    lease_generation integer not null default 0,
    lease_token_id text not null default '',
    lease_expires_at text not null default '',
    stage_code text not null default '',
    progress_basis_points integer not null default 0,
    error_code text not null default '',
    error_summary text not null default '',
    result_available integer not null default 0,
    result_name text not null default '',
    result_mime text not null default '',
    result_bytes integer not null default 0,
    result_sha256 text not null default '',
    retain_until text not null default '',
    prompt_purge_after text not null default '',
    created_at text not null,
    queued_at text not null default '',
    claimed_at text not null default '',
    started_at text not null default '',
    finished_at text not null default '',
    updated_at text not null,
    unique(owner_user_id, operation_id)
  )`,
  `create table if not exists minimax_h3_job_assets (
    asset_id text primary key,
    job_id text not null references minimax_h3_jobs(job_id) on delete cascade,
    owner_user_id text not null references users(id) on delete cascade,
    role text not null check (role in ('first_frame', 'last_frame', 'ref_image', 'ref_video', 'ref_audio', 'storyboard_grid')),
    ordinal integer not null,
    display_name text not null default '',
    declared_mime text not null default '',
    declared_bytes integer not null default 0,
    verified_mime text not null default '',
    verified_bytes integer not null default 0,
    verified_sha256 text not null default '',
    upload_state text not null default 'declared' check (upload_state in ('declared', 'uploading', 'verifying', 'ready', 'failed', 'expired', 'deleted')),
    chunk_size integer not null default 8388608,
    chunk_count integer not null default 0,
    error_code text not null default '',
    created_at text not null,
    completed_at text not null default '',
    updated_at text not null,
    unique(job_id, ordinal)
  )`,
  `create table if not exists minimax_h3_job_events (
    event_id text primary key,
    job_id text not null references minimax_h3_jobs(job_id) on delete cascade,
    seq integer not null,
    actor_type text not null check (actor_type in ('admin', 'runner', 'system')),
    actor_ref text not null default '',
    event_type text not null,
    from_state text not null default '',
    to_state text not null default '',
    code text not null default '',
    summary text not null default '',
    created_at text not null,
    unique(job_id, seq)
  )`,
  `create table if not exists minimax_h3_operation_receipts (
    receipt_id text primary key,
    actor_type text not null,
    actor_ref text not null,
    operation_id text not null,
    action text not null,
    payload_sha256 text not null,
    response_json text not null,
    created_at text not null,
    unique(actor_type, actor_ref, operation_id)
  )`,
  `create table if not exists minimax_h3_transfer_tickets (
    ticket_id text primary key,
    owner_user_id text not null references users(id) on delete cascade,
    runner_id text not null references minimax_h3_runners(runner_id) on delete restrict,
    job_id text not null references minimax_h3_jobs(job_id) on delete cascade,
    asset_id text not null default '',
    direction text not null check (direction in ('upload', 'download', 'preview')),
    secret_sha256 text not null,
    allowed_methods_json text not null,
    max_bytes integer not null default 0,
    status text not null default 'issued' check (status in ('issued', 'consumed', 'revoked', 'expired')),
    expires_at text not null,
    consumed_at text not null default '',
    created_at text not null,
    consumed_by_token_id text not null default ''
  )`,
  "create index if not exists minimax_h3_runners_owner_status_idx on minimax_h3_runners(owner_user_id, status)",
  "create index if not exists minimax_h3_jobs_runner_state_created_idx on minimax_h3_jobs(runner_id, state, created_at)",
  "create index if not exists minimax_h3_jobs_owner_created_idx on minimax_h3_jobs(owner_user_id, created_at desc)",
  "create index if not exists minimax_h3_jobs_lease_state_idx on minimax_h3_jobs(lease_expires_at, state)",
  "create index if not exists minimax_h3_job_assets_job_ordinal_idx on minimax_h3_job_assets(job_id, ordinal)",
  "create index if not exists minimax_h3_job_events_job_seq_idx on minimax_h3_job_events(job_id, seq)",
  "create index if not exists minimax_h3_transfer_tickets_job_status_idx on minimax_h3_transfer_tickets(job_id, status, expires_at)",
  "create index if not exists minimax_h3_transfer_tickets_runner_status_idx on minimax_h3_transfer_tickets(runner_id, status, expires_at)"
]);

export const MINIMAX_H3_TABLE_NAMES = Object.freeze([
  "minimax_h3_runners",
  "minimax_h3_jobs",
  "minimax_h3_job_assets",
  "minimax_h3_job_events",
  "minimax_h3_operation_receipts",
  "minimax_h3_transfer_tickets"
]);
